"""Tests for admin_panel.approved_balance (the approved-pool balance report).

Born July 23 2026: the user approves only fully-clean questions into the
app, and the Layer-7 audit flags jam/harder spots the most (measured ~30%
clean vs ~78% for fold/call on the fresh 20bb batches), so the approved
pool drifts away from the generated balance. The report is pure logic per
the fix-durability rule -- these tests run with no Streamlit runtime.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from admin_panel.approved_balance import (  # noqa: E402
    approved_balance_report,
    balance_axes,
    balance_warnings,
    difficulty_band,
)


def _row(
    answer: str = "Call",
    difficulty: str = "1000",
    pot_type: str = "Single raise pot",
    matchup: str = "BB_vs_HJ",
    chart: str = "plo_6max_20bb",
) -> dict[str, str]:
    return {
        "Correct Answer": answer,
        "Difficulty Rating": difficulty,
        "Preflop Pot Type": pot_type,
        "Position Matchup": matchup,
        "Notes": (
            "Auto-generated by poker-pipeline (PLO preflop path). "
            f"Chart: {chart}. Situation: BB vs HJ, single raise pot, "
            "call_for_value. Node: x/y/z"
        ),
    }


def test_difficulty_band_uses_the_generate_preset_edges():
    # Easy 400-1300, Medium 1300-2100, Hard 2100-3200 -- same as the admin
    # Generate presets, boundary values land in the upper band.
    assert difficulty_band("400") == "Easy"
    assert difficulty_band("1299") == "Easy"
    assert difficulty_band("1300") == "Medium"
    assert difficulty_band("2099") == "Medium"
    assert difficulty_band("2100") == "Hard"
    assert difficulty_band("3200") == "Hard"
    assert difficulty_band("") == "?"
    assert difficulty_band(None) == "?"
    assert difficulty_band("n/a") == "?"


def test_balance_axes_reads_the_csv_columns():
    axes = balance_axes(_row(answer="All-in", difficulty="1419",
                             pot_type="Four bet pot", matchup="UTG_vs_BTN"))
    assert axes == {
        "Difficulty": "Medium",
        "Correct answer": "All-in",
        "Pot type": "Four bet pot",
        "Hero seat": "UTG",
        "Chart": "plo_6max_20bb",
    }


def test_balance_axes_tolerates_missing_columns():
    # Old batches (pre-Notes-rework, no matchup) must bucket as "?", never
    # crash the Review page.
    axes = balance_axes({})
    assert axes["Difficulty"] == "?"
    assert axes["Correct answer"] == "?"
    assert axes["Pot type"] == "?"
    assert axes["Hero seat"] == "?"
    assert axes["Chart"] == "?"


def test_report_counts_shares_and_orders_most_common_first():
    rows = [
        _row(answer="Fold"),
        _row(answer="Fold"),
        _row(answer="Fold"),
        _row(answer="All-in", difficulty="2200"),
    ]
    report = dict(approved_balance_report(rows))
    answers = report["Correct answer"]
    assert answers[0] == ("Fold", 3, 0.75)
    assert answers[1] == ("All-in", 1, 0.25)
    assert report["Difficulty"][0] == ("Easy", 3, 0.75)
    assert ("Hard", 1, 0.25) in report["Difficulty"]


def test_report_empty_pool():
    assert approved_balance_report([]) == []


def test_warnings_fire_on_the_measured_drift_shape():
    # 20 approved: 19 passive, 1 aggressive; all Easy -- BOTH warnings.
    rows = [_row(answer="Fold", difficulty="800") for _ in range(19)]
    rows.append(_row(answer="All-in", difficulty="900"))
    warns = balance_warnings(rows)
    assert len(warns) == 2
    assert "aggressive" in warns[0]
    assert "Medium or Hard" in warns[1]


def test_warnings_quiet_on_a_balanced_pool_and_tiny_pools():
    balanced = (
        [_row(answer="Fold", difficulty="800") for _ in range(4)]
        + [_row(answer="Call", difficulty="1000") for _ in range(4)]
        + [_row(answer="All-in", difficulty="1500") for _ in range(4)]
    )
    assert balance_warnings(balanced) == []
    # Below min_pool: never warn, whatever the mix.
    assert balance_warnings([_row(answer="Fold")] * 5) == []
