"""Tests for pipeline/provenance.py -- the Notes builder and the single
node-reference extraction seam that replaced the solver_reference column.
INVARIANT (pinned here): the Node field round-trips the exact old
solver_reference string, so every downstream node-id/combo parser is
unaffected.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipeline.provenance import (  # noqa: E402
    build_notes,
    node_reference_from_notes,
    parse_notes,
)

_PLO_REF = "plo_9max_100bb/SB/UTG_fold_LJ_raise100_HJ_call_SB_decision"
_POSTFLOP_REF = "BTN_vs_BB_SRP_100bb_QsJd9s_v8/flop:BTN:x/AsKd"


def test_notes_round_trips_the_node_reference_verbatim():
    for ref in (_PLO_REF, _POSTFLOP_REF, ""):
        notes = build_notes(
            "Auto-generated by poker-pipeline (PLO preflop path).",
            chart="plo_9max_100bb",
            situation="SB vs BB, three bet pot, call_for_implied_odds",
            node_ref=ref,
        )
        assert node_reference_from_notes(notes) == ref


def test_node_ref_matches_old_solver_reference_parsing():
    # The consumers do rsplit('/',1)[-1] (node_id for preflop/PLO; combo for
    # postflop) on the extracted ref -- must equal what they got before.
    notes = build_notes("prov.", node_ref=_PLO_REF)
    assert node_reference_from_notes(notes).rsplit("/", 1)[-1] == "UTG_fold_LJ_raise100_HJ_call_SB_decision"
    notes = build_notes("prov.", node_ref=_POSTFLOP_REF)
    assert node_reference_from_notes(notes).rsplit("/", 1)[-1] == "AsKd"


def test_legacy_notes_without_node_field_degrade_to_empty():
    # Old batches: plain provenance, no Node field -> "" (same as a missing
    # solver_reference column).
    assert node_reference_from_notes("Auto-generated by poker-pipeline.") == ""
    assert node_reference_from_notes("") == ""


def test_build_notes_skips_empty_parts():
    assert build_notes("Prov.") == "Prov."
    assert build_notes("Prov.", chart="c") == "Prov. Chart: c."
    assert build_notes("Prov.", node_ref="r") == "Prov. Node: r"


def test_parse_notes_recovers_all_parts():
    notes = build_notes(
        "Auto-generated by poker-pipeline (postflop path).",
        chart="BTN_vs_BB_SRP",
        situation="BTN vs BB, single raised pot, value_bet, dry",
        node_ref=_POSTFLOP_REF,
    )
    parts = parse_notes(notes)
    assert parts.provenance == "Auto-generated by poker-pipeline (postflop path)."
    assert parts.chart == "BTN_vs_BB_SRP"
    assert parts.situation == "BTN vs BB, single raised pot, value_bet, dry"
    assert parts.node_ref == _POSTFLOP_REF


def test_parse_notes_on_legacy_is_all_provenance():
    parts = parse_notes("Auto-generated by poker-pipeline.")
    assert parts.provenance == "Auto-generated by poker-pipeline."
    assert parts.chart == parts.situation == parts.node_ref == ""
