"""Layer 8: Format Writer.

Writes pipeline questions out as CSV rows in the team's question-template
column format. Per docs/engineering_brief.docx, the existing columns stay
unchanged and the pipeline adds 5 new columns: concept_tags, hand_class,
board_texture, solver_reference, ev_gap_bb.

Columns the pipeline cannot fill yet carry an explicit placeholder rather than
being left blank:
  * `[TBD by Layer 6]` -- the question stem, the four options, and the answer
    explanation, all written by the (not-yet-built) LLM Explanation Generator;
  * `[TBD]` -- the cols-A-H UI-rendering fields, whose formatting algorithm the
    brief defers ("the algo to format those will be done last").

Note: the brief states 29 existing columns but its column-group listing names
only 28; this writer uses the 28 named columns plus the 5 new ones.

Uses the standard library `csv` module -- no pandas dependency.
"""
from __future__ import annotations

import csv
from pathlib import Path

from pipeline.fact_extractor.spot_data import SpotData

_LLM_TBD = "[TBD by Layer 6]"     # LLM-generated content
_TBD = "[TBD]"                    # deferred cols-A-H UI formatting

# The question-template columns, in order: 28 existing + 5 new (the brief's
# column groups, then the new pipeline columns 30-34).
CSV_COLUMNS = [
    # UI rendering (brief cols 1-7).
    "User Seat", "User Cards", "Cards on Table", "Table Size",
    "Default Stack", "Seats", "POT",
    # Question content (cols 8-17).
    "Context", "Question", "Question Type", "Hand Stage",
    "Option 1", "Option 2", "Option 3", "Option 4",
    "Correct Answer", "Answer Explanation",
    # Classification (cols 18-24).
    "Cash/Tourney", "Live/Online", "Relative Position", "Preflop Pot Type",
    "Pot Participant", "Stack Depth", "Difficulty Rating",
    # Skill tags (cols 25-27).
    "tag_1", "tag_2", "tag_3",
    # Misc (col 28).
    "Notes",
    # New pipeline columns (cols 30-34).
    "concept_tags", "hand_class", "board_texture", "solver_reference", "ev_gap_bb",
]

_PREFLOP_POT_TYPE = {0: "Limped Pot", 1: "Single Raised Pot",
                     2: "3-Bet Pot", 3: "4-Bet Pot"}


def _bb(value: float) -> str:
    """A stack/blind count formatted as e.g. '98bb'."""
    return f"{round(value)}bb"


def build_row(spot_data: SpotData, difficulty_score: int) -> dict[str, str]:
    """Turn one populated SpotData plus its difficulty into a CSV row dict.

    Every column in CSV_COLUMNS is present; the keys that depend on the LLM or
    on the deferred UI formatter carry an explicit placeholder.
    """
    meta = spot_data.spot_metadata
    decision = spot_data.decision_data
    raise_count = meta.preflop_raise_count

    return {
        # UI rendering -- formatting algorithm deferred by the brief.
        "User Seat": meta.hero_position or _TBD,
        "User Cards": " ".join(meta.hero_cards) or _TBD,
        "Cards on Table": " ".join(meta.board) or _TBD,
        "Table Size": _TBD,
        "Default Stack": _bb(meta.effective_stack_bb),
        "Seats": _TBD,
        "POT": _TBD,
        # Question content -- the LLM writes the prose (Layer 6).
        "Context": _LLM_TBD,
        "Question": _LLM_TBD,
        "Question Type": "Multiple Choice",
        "Hand Stage": meta.street.capitalize(),
        "Option 1": _LLM_TBD,
        "Option 2": _LLM_TBD,
        "Option 3": _LLM_TBD,
        "Option 4": _LLM_TBD,
        "Correct Answer": decision.correct_action or _TBD,
        "Answer Explanation": _LLM_TBD,
        # Classification -- filled from the data block.
        "Cash/Tourney": meta.game_format.capitalize(),
        "Live/Online": _TBD,
        "Relative Position": meta.position_dynamic or _TBD,
        "Preflop Pot Type": _PREFLOP_POT_TYPE.get(raise_count, "Multi-Raised Pot"),
        "Pot Participant": ("Heads-Up" if meta.active_players_on_flop <= 2
                            else "Multiway"),
        "Stack Depth": _bb(meta.stack_depth_bb),
        "Difficulty Rating": str(difficulty_score),
        # Skill tags -- the Phase 3 skill taxonomy, not yet mapped.
        "tag_1": "", "tag_2": "", "tag_3": "",
        "Notes": "Auto-generated by poker-pipeline.",
        # The 5 new pipeline columns.
        "concept_tags": ", ".join(spot_data.concept_tags),
        "hand_class": spot_data.hand_class.label if spot_data.hand_class else "",
        "board_texture": (spot_data.board_texture.composite
                          if spot_data.board_texture else ""),
        "solver_reference": meta.node_id or _TBD,
        "ev_gap_bb": f"{decision.ev_gap_bb:.2f}",
    }


def write_csv(path, rows) -> int:
    """Write question rows to a CSV at `path`; return the number of rows written.

    `rows` is an iterable of (SpotData, difficulty_score) pairs. The parent
    directory is created if needed. The header is always written.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for spot_data, difficulty in rows:
            writer.writerow(build_row(spot_data, difficulty))
            written += 1
    return written
