"""Provenance for the ``Notes`` CSV column (July 2026).

The old cryptic ``solver_reference`` column was folded into ``Notes`` so every
row carries its provenance in one human-readable place: what pipeline made it,
which chart/solve it came from, the exact situation, and the machine node
reference. ``Notes`` now reads, e.g.::

    Auto-generated by poker-pipeline (PLO preflop path). Chart: plo_9max_100bb.
    Situation: SB vs BB, three bet pot, call_for_implied_odds.
    Node: plo_9max_100bb/SB/UTG_fold_..._SB_decision

The ``Node:`` field is the VERBATIM value the removed ``solver_reference``
column held, so every downstream consumer that used to parse solver_reference
(Compare's spot join, the Review range-chart resolver, cross-batch dedup) keeps
working by pulling the same string out of ``Notes`` via
:func:`node_reference_from_notes` -- one tested seam instead of scattered
``row["solver_reference"]`` reads. Old batches (no ``Node:`` field) degrade to
``""``, exactly as a missing solver_reference did.

Pure and dependency-free (like :mod:`pipeline.neutral_credit`) so all five
writers and the admin consumers share one format.
"""

from __future__ import annotations

from dataclasses import dataclass

_CHART = " Chart: "
_SITUATION = " Situation: "
_NODE = " Node: "


def build_notes(
    provenance: str,
    *,
    chart: str = "",
    situation: str = "",
    node_ref: str = "",
) -> str:
    """Assemble the ``Notes`` value from its parts (empty parts are skipped).

    ``provenance`` is the pipeline sentence (kept per-writer). ``node_ref`` is
    the exact old solver_reference string and is always placed LAST so
    :func:`node_reference_from_notes` can recover it unambiguously (node refs
    contain ``/`` and ``_`` but never the ``" Node: "`` delimiter).
    """
    out = provenance.rstrip()
    if chart:
        out += f"{_CHART}{chart}."
    if situation:
        out += f"{_SITUATION}{situation}."
    if node_ref:
        out += f"{_NODE}{node_ref}"
    return out


@dataclass(frozen=True)
class NotesParts:
    provenance: str
    chart: str
    situation: str
    node_ref: str


def parse_notes(notes: str) -> NotesParts:
    """Split a ``Notes`` value back into its parts (missing parts -> "").

    Tolerant of any subset of fields and of the legacy plain-provenance Notes
    (everything before the first known delimiter is the provenance).
    """
    node_ref = node_reference_from_notes(notes)
    head = notes.split(_NODE, 1)[0] if _NODE in notes else notes
    situation = ""
    if _SITUATION in head:
        head, sit = head.split(_SITUATION, 1)
        situation = sit.rstrip().removesuffix(".")
    chart = ""
    if _CHART in head:
        head, ch = head.split(_CHART, 1)
        chart = ch.rstrip().removesuffix(".")
    return NotesParts(head.rstrip(), chart, situation, node_ref)


def node_reference_from_notes(notes: str) -> str:
    """The machine node reference (old ``solver_reference`` value), or ``""``.

    Everything after the last ``" Node: "`` delimiter. This is the ONE seam
    every consumer that used to read ``row["solver_reference"]`` now goes
    through, so the node-id / combo parsing they do on the result is unchanged.
    """
    if _NODE not in notes:
        return ""
    return notes.rsplit(_NODE, 1)[-1].strip()


__all__ = [
    "NotesParts",
    "build_notes",
    "node_reference_from_notes",
    "parse_notes",
]
