"""Layer 8 (postflop): write the question rows to CSV.

Builds a row dict per question in a column layout aligned with the team's
output format (the table-state columns the app renders, the question/options/
explanation, the classification block, and the postflop diagnostics), then
writes the CSV. Deterministic; no LLM.

Amounts render in big blinds for v1 (the IR is bb-denominated). A follow-up
can port the preflop ``app_table_format`` engine to emit the exact Runout
chip/seat token strings (e.g. ``User Seat = "BTN-$97-..."``) for the
dollar-denominated table renderer; that is a formatting concern, not a
pipeline one, so it does not touch any layer above this.
"""

from __future__ import annotations

import csv
from collections.abc import Iterable
from pathlib import Path

from pipeline.explanation_generator import GeneratedExplanation
from pipeline.neutral_credit import format_neutral_credit, neutral_credit_options
from pipeline.postflop.action_history import build_context_line, format_question
from pipeline.postflop.difficulty import PostflopDifficulty
from pipeline.postflop.facts import PostflopFacts
from pipeline.postflop.options import frequencies_for_options
from pipeline.postflop.solve import PostflopSolve
from pipeline.postflop.spot_sampler import spot_action_evs_bb

# The postflop CSV schema. A focused, documented column set: the app table
# state, the question content, the classification block, and the postflop
# diagnostics. (The preflop pipeline has its own 40-column writer; postflop is
# deliberately separate so neither can disturb the other.)
POSTFLOP_CSV_COLUMNS: tuple[str, ...] = (
    "No",
    "Hand Stage",
    "Context",
    "User Seat",
    "User Cards",
    "Cards on Table",
    "Table Size",
    "Default Stack",
    "POT",
    "Question",
    "Question Type",
    "option 1",
    "option 2",
    "option 3",
    "option 4",
    "Correct Answer",
    # Deterministic neutral-credit options (the 20-point rule); "" when the
    # spot has one clear answer. Right after Correct Answer, like the other paths.
    "neutral_credit",
    "Answer Explanation",
    "Cash/Tourney",
    "Live or Online",
    "Relative Position",
    "Position Matchup",
    "Difficulty Rating",
    "action_frequencies",
    # Per-action solver EV (bb) for the hero hand, ordered to match
    # action_frequencies -- the full per-option breakdown (replaced the
    # single-number ev_gap_bb column, mirroring the preflop writer; the gap is
    # still computed internally for the worthiness gate + difficulty).
    "action_ev_bb",
    "hero_equity",
    "pot_odds",
    "spr",
    "concept_tags",
    "archetype",
    "board_texture",
    "easy_freq",
    "easy_ev",
    "Notes",
    "solver_reference",
    "validation_status",
)

_NOTES = "Auto-generated by poker-pipeline (postflop path)."


def _emoji_cards(cards: Iterable[str]) -> str:
    from pipeline.action_history import format_card  # local: pure leaf

    return " ".join(format_card(c) for c in cards)


def _format_frequencies(action_frequencies: dict[str, float]) -> str:
    """'Bet 75%: 70%, Bet 33%: 20%, Check: 10%' (descending), skipping ~0."""
    items = sorted(action_frequencies.items(), key=lambda kv: -kv[1])
    return ", ".join(
        f"{label}: {freq * 100:.0f}%" for label, freq in items if freq >= 0.005
    )


def _format_action_evs(
    evs: dict[str, float] | None, action_frequencies: dict[str, float]
) -> str:
    """The ``action_ev_bb`` CSV value, e.g. ``"Check: +4.10, Bet 75%: +4.05"``.

    Ordered by descending action frequency so it lines up column-for-column
    with ``action_frequencies``; each EV is in bb to two decimals with an
    explicit sign. ``None`` (the solve exposes no per-action EVs) -> "".
    """
    if not evs:
        return ""
    ordered = sorted(evs, key=lambda label: -action_frequencies.get(label, 0.0))
    return ", ".join(f"{label}: {evs[label]:+.2f}" for label in ordered)


def build_postflop_row(
    facts: PostflopFacts,
    explanation: GeneratedExplanation,
    solve: PostflopSolve,
    difficulty: PostflopDifficulty,
    number: int,
    *,
    validation_status: str = "draft",
    display_in_bb: bool = True,
) -> dict[str, str]:
    """Build one CSV row dict from all the layer outputs.

    Amounts in the Context / Question / POT / Default Stack render in big blinds
    (``display_in_bb=True``) or in dollars (``solve.bb_in_dollars``). The
    ``action_ev_bb`` / SPR / equity columns are unit-fixed and unaffected.
    """
    from pipeline.postflop.action_history import make_amount_fmt  # noqa: PLC0415

    node = facts.spot.node
    amt = make_amount_fmt(display_in_bb=display_in_bb, bb_in_dollars=solve.bb_in_dollars)
    opts = (explanation.options() + ["", "", "", ""])[:4]
    pot_odds = (
        f"{facts.break_even_equity * 100:.0f}%"
        if facts.break_even_equity is not None
        else ""
    )
    row = {
        "No": str(number),
        "Hand Stage": facts.street.capitalize(),
        "Context": build_context_line(solve, display_in_bb=display_in_bb),
        "User Seat": facts.hero_position,
        "User Cards": _emoji_cards(facts.spot.hero_cards),
        "Cards on Table": _emoji_cards(facts.board),
        "Table Size": str(solve.table_size),
        "Default Stack": amt(node.effective_stack_bb),
        "POT": amt(facts.pot_bb),
        "Question": format_question(facts.spot, solve, display_in_bb=display_in_bb),
        "Question Type": "Postflop Decision",
        "option 1": opts[0],
        "option 2": opts[1],
        "option 3": opts[2],
        "option 4": opts[3],
        "Correct Answer": explanation.correct_answer,
        # Neutral-credit options from the hand's own action mix (the 20-point
        # rule). frequencies_for_options sums collapsed verb families (a "Bet"
        # option = "Bet 33%" + "Bet 50%" + ...) so neutral credit matches the
        # options even when gto collapsed a multi-size spot to Check-vs-Bet.
        "neutral_credit": format_neutral_credit(
            neutral_credit_options(
                explanation.options(),
                explanation.correct_answer,
                frequencies_for_options(
                    facts.spot.action_frequencies, explanation.options()
                ),
            )
        ),
        "Answer Explanation": explanation.answer_explanation,
        "Cash/Tourney": "Tournament" if solve.game_format == "tournament" else "Cash",
        "Live or Online": solve.live_or_online,
        "Relative Position": "In Position" if facts.hero_in_position else "Out of Position",
        "Position Matchup": f"{facts.hero_position}_vs_{facts.villain_position}",
        "Difficulty Rating": str(difficulty.score),
        "action_frequencies": _format_frequencies(facts.spot.action_frequencies),
        "action_ev_bb": _format_action_evs(
            spot_action_evs_bb(facts.spot), facts.spot.action_frequencies
        ),
        "hero_equity": f"{facts.hero_equity_vs_villain * 100:.0f}%",
        "pot_odds": pot_odds,
        "spr": f"{facts.spr:.1f}",
        "concept_tags": ", ".join(facts.concept_tags),
        "archetype": facts.archetype,
        "board_texture": facts.board_texture.get("composite", ""),
        "easy_freq": f"{difficulty.easy_freq:.2f}",
        "easy_ev": f"{difficulty.easy_ev:.2f}" if difficulty.easy_ev is not None else "",
        "Notes": _NOTES,
        "solver_reference": f"{solve.source_reference}/{node.node_id}/{facts.spot.hero_combo}",
        "validation_status": validation_status,
    }
    return row


def write_postflop_csv(output_path: Path | str, rows: list[dict[str, str]]) -> int:
    """Write row dicts to ``output_path`` (UTF-8 BOM for Excel). Returns count."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(POSTFLOP_CSV_COLUMNS))
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in POSTFLOP_CSV_COLUMNS})
    return len(rows)


__all__ = ["POSTFLOP_CSV_COLUMNS", "build_postflop_row", "write_postflop_csv"]
