"""Layer 8 (postflop): write the question rows to CSV.

Builds a row dict per question in a column layout aligned with the team's
output format (the table-state columns the app renders, the question/options/
explanation, the classification block, and the postflop diagnostics), then
writes the CSV. Deterministic; no LLM.

The table-state columns (User Seat / User Cards / Cards on Table / Table Size /
Default Stack / Seats / POT) are the Runout app's exact chip/seat/board render
tokens, built by :mod:`pipeline.postflop.app_table_format` from the same
bb-denominated amounts the question prose uses. They render in big blinds
(``display_in_bb=True``) or in dollars (``solve.bb_in_dollars``).
"""

from __future__ import annotations

import csv
from collections.abc import Iterable
from pathlib import Path

from pipeline.chat_context import StrategyEntry, build_chat_context
from pipeline.explanation_generator import GeneratedExplanation
from pipeline.neutral_credit import format_neutral_credit, neutral_credit_options
from pipeline.postflop.action_history import build_context_line, format_question
from pipeline.postflop.app_table_format import build_postflop_app_table_columns
from pipeline.postflop.difficulty import PostflopDifficulty
from pipeline.postflop.facts import PostflopFacts
from pipeline.postflop.options import frequencies_for_options
from pipeline.postflop.skills import compute_postflop_skills
from pipeline.postflop.solve import PostflopSolve
from pipeline.postflop.spot_sampler import spot_action_evs_bb

# The postflop CSV schema. A focused, documented column set: the app table
# state, the question content, the classification block, and the postflop
# diagnostics. (The preflop pipeline has its own 40-column writer; postflop is
# deliberately separate so neither can disturb the other.)
POSTFLOP_CSV_COLUMNS: tuple[str, ...] = (
    "No",
    "Hand Stage",
    "Context",
    "User Seat",
    "User Cards",
    "Cards on Table",
    "Table Size",
    "Default Stack",
    # Villain seat tokens in the app's poker-table format (e.g.
    # "BB-$95.7-$1.8-bet"); same grammar as User Seat. Built by
    # pipeline/postflop/app_table_format.py. Sits between Default Stack and POT,
    # matching the app's table-state column order.
    "Seats",
    "POT",
    "Question",
    "Question Type",
    "option 1",
    "option 2",
    "option 3",
    "option 4",
    "Correct Answer",
    # Deterministic neutral-credit options (the 20-point rule); "" when the
    # spot has one clear answer. Right after Correct Answer, like the other paths.
    "neutral_credit",
    "Answer Explanation",
    "Cash/Tourney",
    "Live or Online",
    "Relative Position",
    "Position Matchup",
    "Difficulty Rating",
    "action_frequencies",
    # Per-action solver EV (bb) for the hero hand, ordered to match
    # action_frequencies -- the full per-option breakdown (replaced the
    # single-number ev_gap_bb column, mirroring the preflop writer; the gap is
    # still computed internally for the worthiness gate + difficulty).
    "action_ev_bb",
    "hero_equity",
    # Node-level range-vs-range equity (the actor's whole range vs villain's on
    # this board) -- the "who is ahead here" number. The resolved verdict
    # (range_advantage / nut_advantage) rides in concept_tags.
    "range_equity",
    "pot_odds",
    "spr",
    "concept_tags",
    # User-facing skill labels (the app's catalog) mapped from the facts -- the
    # postflop analogue of the preflop `skills` column. See pipeline/postflop/skills.py.
    "skills",
    "archetype",
    "board_texture",
    # Difficulty-axis diagnostics (3-axis: freq + concept + hand; easy_ev is a
    # diagnostic only, NOT in the score -- see difficulty.py).
    "easy_freq",
    "easy_ev",
    "easy_concept",
    "easy_hand",
    "Notes",
    "solver_reference",
    "validation_status",
    # Per-question chatbot context: one JSON blob of ALL deterministic facts for
    # the app's "chat about this question" AI (full strategy + EVs, equity,
    # range/nut advantage, blockers, villain summary, the answer + alternatives,
    # the explanation shown, and a guardrails line). See pipeline/chat_context.py.
    "chat_context",
    # Layer-7 claim-checker output (opt-in): "" = not run, "[]" = run + clean,
    # a JSON list of {claim, problem} = flagged. Same shape as the preflop
    # column, so the admin Review panel reads it with the same parser.
    "claim_check",
)

_NOTES = "Auto-generated by poker-pipeline (postflop path)."


def _emoji_cards(cards: Iterable[str]) -> str:
    from pipeline.action_history import format_card  # local: pure leaf

    return " ".join(format_card(c) for c in cards)


def _format_frequencies(action_frequencies: dict[str, float]) -> str:
    """'Bet 75%: 70%, Bet 33%: 20%, Check: 10%' (descending), skipping ~0."""
    items = sorted(action_frequencies.items(), key=lambda kv: -kv[1])
    return ", ".join(
        f"{label}: {freq * 100:.0f}%" for label, freq in items if freq >= 0.005
    )


def _format_action_evs(
    evs: dict[str, float] | None, action_frequencies: dict[str, float]
) -> str:
    """The ``action_ev_bb`` CSV value, e.g. ``"Check: +4.10, Bet 75%: +4.05"``.

    Ordered by descending action frequency so it lines up column-for-column
    with ``action_frequencies``; each EV is in bb to two decimals with an
    explicit sign. ``None`` (the solve exposes no per-action EVs) -> "".
    """
    if not evs:
        return ""
    ordered = sorted(evs, key=lambda label: -action_frequencies.get(label, 0.0))
    return ", ".join(f"{label}: {evs[label]:+.2f}" for label in ordered)


def _postflop_chat_context(
    facts: PostflopFacts,
    explanation: GeneratedExplanation,
    solve: PostflopSolve,
    difficulty: PostflopDifficulty,
    *,
    display_in_bb: bool,
    neutral: list[str],
) -> str:
    """The per-question chatbot JSON blob (all deterministic facts). See
    :mod:`pipeline.chat_context`."""
    from pipeline.postflop.explanation_generator import (  # noqa: PLC0415
        POSTFLOP_ARCHETYPE_GUIDANCE,
    )
    from pipeline.postflop.skills import compute_postflop_skills  # noqa: PLC0415

    evs = spot_action_evs_bb(facts.spot) or {}
    strategy = [
        StrategyEntry(action=label, frequency_pct=freq * 100.0, ev_bb=evs.get(label))
        for label, freq in facts.spot.action_frequencies.items()
    ]
    key_facts: dict[str, object] = {
        "hero_equity_vs_villain_pct": round(facts.hero_equity_vs_villain * 100),
        # Showdown-equity composition: what share of villain's range hero beats
        # RIGHT NOW (so the chatbot can explain "ahead of air" vs "drawing").
        "currently_ahead_of_villain_range_pct": round(facts.currently_ahead_pct * 100),
        "your_range_equity_pct": round(facts.hero_range_equity * 100),
        "range_advantage": facts.range_advantage,
        "nut_advantage": facts.nut_advantage,
        "spr": round(facts.spr, 1),
        "pot_bb": round(facts.pot_bb, 1),
        "board_texture": facts.board_texture.get("composite", ""),
    }
    if facts.break_even_equity is not None:
        key_facts["break_even_equity_pct"] = round(facts.break_even_equity * 100)
        key_facts["to_call_bb"] = round(facts.to_call_bb, 1)
    if facts.blocker_effect != "neutral":
        key_facts["blockers"] = (
            f"you remove ~{facts.blocked_value_pct * 100:.0f}% of villain's value "
            f"and ~{facts.blocked_bluff_pct * 100:.0f}% of their bluffs "
            f"(mainly block their {facts.blocker_effect})"
        )
    villain = {
        "seat": facts.villain_position,
        "strong_hands_pct": round(facts.villain_nut_share * 100),
        "has_range_edge": facts.range_advantage == "villain",
    }
    return build_chat_context(
        pipeline="postflop",
        situation=format_question(facts.spot, solve, display_in_bb=display_in_bb),
        hero_hand=_emoji_cards(facts.spot.hero_cards),
        hand_summary=f"{facts.made_hand.replace('_', ' ')} ({facts.strength_bucket})"
        + (f"; draws: {', '.join(facts.draws)}" if facts.has_strong_draw else ""),
        recommended_action=explanation.correct_answer,
        also_acceptable=neutral,
        full_strategy=strategy,
        key_facts=key_facts,
        villain=villain,
        strategic_frame=f"{facts.archetype}: "
        f"{POSTFLOP_ARCHETYPE_GUIDANCE.get(facts.archetype, '')}",
        concept_tags=facts.concept_tags,
        skills_tested=compute_postflop_skills(facts, game_format=solve.game_format),
        difficulty=difficulty.score,
        coaching_answer=explanation.answer_explanation,
    )


def build_postflop_row(
    facts: PostflopFacts,
    explanation: GeneratedExplanation,
    solve: PostflopSolve,
    difficulty: PostflopDifficulty,
    number: int,
    *,
    validation_status: str = "draft",
    display_in_bb: bool = True,
) -> dict[str, str]:
    """Build one CSV row dict from all the layer outputs.

    Amounts in the Context / Question / POT / Default Stack render in big blinds
    (``display_in_bb=True``) or in dollars (``solve.bb_in_dollars``). The
    ``action_ev_bb`` / SPR / equity columns are unit-fixed and unaffected.
    """
    node = facts.spot.node
    # The app's poker-table render tokens (seats + chips + board), so the CSV
    # feeds the chip/seat/board renderer directly. Built from the same resolved
    # amounts as the Question prose, so the two never disagree.
    table = build_postflop_app_table_columns(facts, solve, display_in_bb=display_in_bb)
    opts = (explanation.options() + ["", "", "", ""])[:4]
    pot_odds = (
        f"{facts.break_even_equity * 100:.0f}%"
        if facts.break_even_equity is not None
        else ""
    )
    # Neutral-credit options from the hand's own action mix (the 20-point rule);
    # computed once, reused by the neutral_credit column + the chatbot context.
    neutral_list = neutral_credit_options(
        explanation.options(),
        explanation.correct_answer,
        frequencies_for_options(facts.spot.action_frequencies, explanation.options()),
    )
    row = {
        "No": str(number),
        "Hand Stage": facts.street.capitalize(),
        "Context": build_context_line(solve, display_in_bb=display_in_bb),
        # App table-state tokens (User Seat / User Cards / Cards on Table /
        # Table Size / Default Stack / Seats / POT) -- see app_table_format.py.
        "User Seat": table["user_seat"],
        "User Cards": table["user_cards"],
        "Cards on Table": table["cards_on_table"],
        "Table Size": table["table_size"],
        "Default Stack": table["default_stack"],
        "Seats": table["seats"],
        "POT": table["pot"],
        "Question": format_question(facts.spot, solve, display_in_bb=display_in_bb),
        # Same fixed label as the preflop/PLO writers, no trailing period
        # (June 2026 -- was "Postflop Decision"; unified per team feedback).
        "Question Type": "Hand Scenario Question",
        "option 1": opts[0],
        "option 2": opts[1],
        "option 3": opts[2],
        "option 4": opts[3],
        "Correct Answer": explanation.correct_answer,
        # frequencies_for_options sums collapsed verb families (a "Bet" option =
        # "Bet 33%" + "Bet 50%" + ...) so neutral credit matches the options even
        # when gto collapsed a multi-size spot to Check-vs-Bet.
        "neutral_credit": format_neutral_credit(neutral_list),
        "Answer Explanation": explanation.answer_explanation,
        "Cash/Tourney": "Tournament" if solve.game_format == "tournament" else "Cash",
        "Live or Online": solve.live_or_online,
        "Relative Position": "In Position" if facts.hero_in_position else "Out of Position",
        "Position Matchup": f"{facts.hero_position}_vs_{facts.villain_position}",
        "Difficulty Rating": str(difficulty.score),
        "action_frequencies": _format_frequencies(facts.spot.action_frequencies),
        "action_ev_bb": _format_action_evs(
            spot_action_evs_bb(facts.spot), facts.spot.action_frequencies
        ),
        "hero_equity": f"{facts.hero_equity_vs_villain * 100:.0f}%",
        "range_equity": f"{facts.hero_range_equity * 100:.0f}%",
        "pot_odds": pot_odds,
        "spr": f"{facts.spr:.1f}",
        "concept_tags": ", ".join(facts.concept_tags),
        "skills": ", ".join(
            compute_postflop_skills(facts, game_format=solve.game_format)
        ),
        "archetype": facts.archetype,
        "board_texture": facts.board_texture.get("composite", ""),
        "easy_freq": f"{difficulty.easy_freq:.2f}",
        "easy_ev": f"{difficulty.easy_ev:.2f}" if difficulty.easy_ev is not None else "",
        "easy_concept": f"{difficulty.easy_concept:.2f}",
        "easy_hand": f"{difficulty.easy_hand:.2f}",
        "Notes": _NOTES,
        "solver_reference": f"{solve.source_reference}/{node.node_id}/{facts.spot.hero_combo}",
        "validation_status": validation_status,
        "chat_context": _postflop_chat_context(
            facts, explanation, solve, difficulty,
            display_in_bb=display_in_bb, neutral=neutral_list,
        ),
        # "" = the Layer-7 claim checker did not run for this row. The batch
        # overwrites this with the checker's JSON when the opt-in pass runs.
        "claim_check": "",
    }
    return row


def write_postflop_csv(output_path: Path | str, rows: list[dict[str, str]]) -> int:
    """Write row dicts to ``output_path`` (UTF-8 BOM for Excel). Returns count."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(POSTFLOP_CSV_COLUMNS))
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in POSTFLOP_CSV_COLUMNS})
    return len(rows)


__all__ = ["POSTFLOP_CSV_COLUMNS", "build_postflop_row", "write_postflop_csv"]
