"""Build the `templates/Cash6max_100bb_BTN_open_BB_call_ryan_ranges.txt`
template by cloning PioSolver's `2bpot-full.txt` and replacing the
`set_range OOP` / `set_range IP` lines with vectors derived from Ryan's
preflop range pack.

What this does, step by step:

  1. Reads PioSolver's shipped template at
     `C:\\PioSOLVER\\TreeBuilding\\100bb\\2bpot-full.txt`.
  2. Reads Ryan's two range files for the BTN-vs-BB SRP scenario:
       OOP: `<pack>/BB/UTG_Fold_HJ_Fold_CO_Fold_BTN_60%_SB_Fold_BB_Call.txt`
       IP : `<pack>/BTN/UTG_Fold_HJ_Fold_CO_Fold_BTN_60%.txt`
  3. Expands each 169-hand-class file to a 1326-combo weight vector in
     PioSolver's canonical hand-order via `pipeline.preflop_ranges`.
  4. Replaces the template's two `set_range` lines with the expanded vectors,
     leaves every other line intact (sizings, `add_line` tree, build_tree).
  5. Writes the result to
     `templates/Cash6max_100bb_BTN_open_BB_call_ryan_ranges.txt`.

This is a one-time build step. Re-run it only when Ryan ships an updated
pack or the source template changes. The output is checked in so the batch
solver can read it directly.

Usage:
    python scripts/build_ryan_ranges_template.py
    python scripts/build_ryan_ranges_template.py --check        # diff vs. existing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from pipeline.preflop_ranges import (                                       # noqa: E402
    expand_to_combo_weights, format_set_range_line, parse_range_file,
)

SOURCE_TEMPLATE = Path(r"C:\PioSOLVER\TreeBuilding\100bb\2bpot-full.txt")
RANGE_PACK_ROOT = (REPO_ROOT / "ranges" / "ryan_preflop_tree"
                   / "PioViewer - NLH 6max 100bb 2.5x Open")
OOP_RANGE_FILE = (RANGE_PACK_ROOT / "BB"
                  / "UTG_Fold_HJ_Fold_CO_Fold_BTN_60%_SB_Fold_BB_Call.txt")
IP_RANGE_FILE = (RANGE_PACK_ROOT / "BTN"
                 / "UTG_Fold_HJ_Fold_CO_Fold_BTN_60%.txt")
OUTPUT_TEMPLATE = (REPO_ROOT / "templates"
                   / "Cash6max_100bb_BTN_open_BB_call_ryan_ranges.txt")

# Marker comments inserted ahead of each set_range line so the template is
# self-describing -- a reader can see at a glance which file each vector
# came from. Lines starting with `#` are skipped by the batch solver.
HEADER = """\
# Cash 6-max 100bb BTN-vs-BB SRP -- ranges from Ryan's preflop pack.
#
# Generated by scripts/build_ryan_ranges_template.py from:
#   OOP: ranges/ryan_preflop_tree/.../BB/UTG_Fold_HJ_Fold_CO_Fold_BTN_60%_SB_Fold_BB_Call.txt
#   IP : ranges/ryan_preflop_tree/.../BTN/UTG_Fold_HJ_Fold_CO_Fold_BTN_60%.txt
#
# Sizings (add_line entries, #FlopConfig.BetSize, etc.) and the build_tree
# command are cloned verbatim from PioSolver's shipped 2bpot-full.txt.
"""


def build(*, check_only: bool = False) -> int:
    if not SOURCE_TEMPLATE.is_file():
        print(f"ERROR: source template not found: {SOURCE_TEMPLATE}",
              file=sys.stderr)
        return 2
    for label, path in (("OOP", OOP_RANGE_FILE), ("IP", IP_RANGE_FILE)):
        if not path.is_file():
            print(f"ERROR: Ryan {label} range file not found: {path}",
                  file=sys.stderr)
            return 2

    print(f"Source template     : {SOURCE_TEMPLATE}")
    print(f"OOP range file (BB) : {OOP_RANGE_FILE.relative_to(REPO_ROOT)}")
    print(f"IP  range file (BTN): {IP_RANGE_FILE.relative_to(REPO_ROOT)}")
    print()

    oop_classes = parse_range_file(OOP_RANGE_FILE)
    ip_classes = parse_range_file(IP_RANGE_FILE)
    oop_weights = expand_to_combo_weights(oop_classes)
    ip_weights = expand_to_combo_weights(ip_classes)
    print(f"OOP (BB call vs BTN): {sum(oop_weights):>6.1f} weighted combos "
          f"({100 * sum(oop_weights) / 1326:.1f}% of all hands)")
    print(f"IP  (BTN RFI)       : {sum(ip_weights):>6.1f} weighted combos "
          f"({100 * sum(ip_weights) / 1326:.1f}% of all hands)")

    source_lines = SOURCE_TEMPLATE.read_text(encoding="utf-8").splitlines()
    new_oop_line = format_set_range_line("OOP", oop_weights)
    new_ip_line = format_set_range_line("IP", ip_weights)

    output_lines: list[str] = HEADER.splitlines()
    oop_replaced = ip_replaced = False
    for line in source_lines:
        stripped = line.lstrip()
        if stripped.startswith("set_range OOP "):
            output_lines.append(new_oop_line)
            oop_replaced = True
        elif stripped.startswith("set_range IP "):
            output_lines.append(new_ip_line)
            ip_replaced = True
        else:
            output_lines.append(line)
    if not oop_replaced or not ip_replaced:
        print(f"ERROR: source template missing set_range OOP/IP lines "
              f"(oop_found={oop_replaced}, ip_found={ip_replaced})",
              file=sys.stderr)
        return 3

    new_content = "\n".join(output_lines) + "\n"

    if check_only:
        if not OUTPUT_TEMPLATE.is_file():
            print(f"\ncheck: output template missing at {OUTPUT_TEMPLATE}")
            return 1
        current = OUTPUT_TEMPLATE.read_text(encoding="utf-8")
        if current == new_content:
            print(f"\ncheck: {OUTPUT_TEMPLATE.relative_to(REPO_ROOT)} is up to date.")
            return 0
        print(f"\ncheck: {OUTPUT_TEMPLATE.relative_to(REPO_ROOT)} is OUT OF DATE; "
              f"re-run without --check to regenerate.")
        return 1

    OUTPUT_TEMPLATE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TEMPLATE.write_text(new_content, encoding="utf-8")
    print(f"\nwrote: {OUTPUT_TEMPLATE.relative_to(REPO_ROOT)} "
          f"({len(new_content):,} bytes)")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the existing output template "
                             "would change; do not write anything")
    args = parser.parse_args(argv)
    return build(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
